Repository be15-fin-Nexus-SION/be15-fin-Nexus-SION-FE, pull requests merged in 2025-07, with the labels that each got.

#74 Feat/46 project list
  src/api/project.js
  src/components/Pagination.vue
  src/features/project/components/FilterSidebar.vue
  src/features/project/components/ProjectCard.vue
  src/features/project/views/ProjectListView.vue
Labels: feat, FE, V1

#85 [feat] 헤더 모달 작업
  src/components/header/AuthMenu.vue
Labels: feat, FE, V1

#89 Feat/49 project register
  src/api/clientCompany.js
  src/api/document.js
  src/api/domain.js
  src/api/job.js
  src/api/project.js
  src/components/DropdownSelect.vue
  src/features/project/router.js
  src/features/project/views/ProjectListView.vue
  src/features/project/views/ProjectRegisterView.vue
Labels: feat, FE, V1

#91 techstackselectmodal import 수정
  src/features/project/views/ProjectRegisterView.vue
Labels: refactor, FE, V1

#96 [fix] techstack modal import 수정
  index.html
  src/features/developer/views/DeveloperEditView.vue
Labels: FE, V1, BUG🐞, test

#104 [feat] 개발자 목록에 등급, 역할 필터 적용
  index.html
  src/api/member.js
  src/components/dropdown/SortDropdown.vue
  src/features/developer/components/RadarChart.vue
  src/features/developer/views/DeveloperDetailView.vue
  src/features/developer/views/DeveloperEditView.vue
  src/features/developer/views/DeveloperListView.vue
Labels: feat, FE, V2

#94 [feat] memberRole 에 따른 페이지 권한 부여
  src/components/header/AuthMenu.vue
  src/components/header/HeaderMain.vue
  src/features/admin/router.js
  src/features/auth/views/LoginView.vue
  src/features/auth/views/SignupView.vue
  src/features/developer/router.js
  src/features/statistics/router.js
  src/main.js
  src/router/index.js
Labels: feat, FE, V2

#107 프로젝트 수정
  src/api/project.js
  src/features/project/components/ProjectEditForm.vue
  src/features/project/router.js
  src/features/project/views/ProjectDetailView.vue
Labels: feat, FE, V1

#115 [Feat] 스쿼드 가져오기 및 수정하기 기능 구현
  src/api/squad.js
  src/features/squad/components/ExistSquadCard.vue
  src/features/squad/components/create/SquadCreateSection.vue
  src/features/squad/components/create/SquadFilterSection.vue
  src/stores/squadCreateStore.js
Labels: feat, FE, V1

#117 [feat] 프로젝트 등록 페이지 라우터 추가
  src/features/squad/components/SquadSidebar.vue
Labels: feat, FE, V1

#119 Feat/118 freelancer UI
  src/features/developer/views/DeveloperListView.vue
  src/features/freelancer/components/FreelancerCard.vue
  src/features/freelancer/components/FreelancerDetailPanel.vue
  src/features/freelancer/router.js
  src/features/freelancer/views/FreelancerListView.vue
  src/router/index.js
Labels: feat, FE, V2

#120 [Feat] 스쿼드 전체 기능 구현 및 리팩토링
  src/api/squad.js
  src/composable/useSquadSelect.js
  src/features/squad/components/AiRecommendationModal.vue
  src/features/squad/components/ProjectListModal.vue
  src/features/squad/components/SquadCard.vue
  src/features/squad/components/SquadCostTable.vue
  src/features/squad/components/SquadDropdown.vue
  src/features/squad/components/SquadInfo.vue
  src/features/squad/components/SquadMemberList.vue
  src/features/squad/components/SquadSidebar.vue
  src/features/squad/components/SquadSidebarSection.vue
  src/features/squad/components/create/SquadCardList.vue
  src/features/squad/components/create/SquadCreateSection.vue
  src/features/squad/components/create/SquadFilterSection.vue
  src/features/squad/components/presentation/SquadMemberRenderer.vue
  src/features/squad/views/SquadCreateView.vue
  src/features/squad/views/SquadDetailView.vue
  src/features/squad/views/SquadListView.vue
  src/stores/squadCreateStore.js
Labels: feat, FE, V1

#126 [Feat] 스쿼드 애니메이션 기능 추가
  src/features/squad/components/SquadCard.vue
  src/features/squad/components/SquadInfo.vue
  src/features/squad/components/SquadSidebar.vue
  src/features/squad/components/SquadSidebarSection.vue
  src/features/squad/components/create/AiRecommendedSection.vue
  src/features/squad/components/create/ManualDeveloperList.vue
  src/features/squad/components/create/SquadFilterSection.vue
  src/features/squad/views/SquadDetailView.vue
  src/features/squad/views/SquadListView.vue
Labels: refactor, FE, V2

#131 [feat] 관리자 자격증 종류 CRUD 페이지 구현
  package-lock.json
  src/api/member.js
  src/components/side/SidebarWrapper.vue
  src/features/admin/components/CertificateTypeModal.vue
  src/features/admin/router.js
  src/features/admin/views/AdminCertificateTypeSetting.vue
  src/features/squad/router.js
Labels: feat, FE, V2

#133 프로젝트 프론트 ui 수정
  src/features/freelancer/components/FreelancerDetailPanel.vue
  src/features/project/views/ProjectDetailView.vue
  src/features/project/views/ProjectRegisterView.vue
Labels: feat, FE, V1, V2

#141 [feat] 관리자 자격증 승인/반려 UI 및 기능 구현
  src/api/member.js
  src/components/side/SidebarWrapper.vue
  src/features/admin/components/CertificateTypeModal.vue
  src/features/admin/router.js
  src/features/admin/views/AdminCertificateApprovalView.vue
  src/features/admin/views/AdminCertificateTypeSetting.vue
Labels: feat, FE, V2

#135 [feat] 프로젝트 이력 등록 조회, 요청하는 페이지 구현
  src/api/project.js
  src/components/badge/ProjectHistoryStatusBadge.vue
  src/features/project/components/AlreadyRequestedModal.vue
  src/features/project/components/ProjectHistoryItem.vue
  src/features/project/components/ProjectHistoryList.vue
  src/features/project/components/ProjectHistoryQueryCard.vue
  src/features/project/components/ProjectHistoryRegisterCard.vue
  src/features/project/components/ProjectModal.vue
  src/features/project/components/StatusFilter.vue
  src/features/project/router.js
  src/features/project/views/ProjectHIstoryListView.vue
  src/features/project/views/ProjectHistoryDetailView.vue
  src/features/project/views/ProjectHistoryRegisterView.vue
  src/features/project/views/ProjectListView.vue
Labels: feat, FE, V2

#142 [Feat] 스쿼드 개발자 상세 조회 모달 구현 및 전체적인 기능 리팩토링
  src/App.vue
  src/api/project.js
  src/composable/useDeveloperModal.js
  src/features/developer/views/DeveloperDetailView.vue
  src/features/project/components/ProjectCard.vue
  src/features/project/components/ProjectEditForm.vue
  src/features/project/views/ProjectDetailView.vue
  src/features/project/views/ProjectRegisterView.vue
  src/features/squad/components/SquadCard.vue
  src/features/squad/components/SquadMemberList.vue
  src/features/squad/components/create/AiRecommendedSection.vue
  src/features/squad/components/create/ManualDeveloperList.vue
  src/features/squad/components/create/SquadCardList.vue
  src/features/squad/components/create/SquadCreateSection.vue
  src/features/squad/components/create/SquadFilterSection.vue
  src/features/squad/components/modal/DeveloperDetailModal.vue
  src/features/squad/components/presentation/SquadMemberRenderer.vue
  src/features/squad/views/SquadDetailView.vue
  src/stores/squadProject.js
Labels: feat, refactor, FE, V2

#152 [Refactor]: 스쿼드 권한 설정 및 애니메이션 바우스 스타일 추가
  src/components/header/AuthMenu.vue
  src/features/squad/router.js
  src/router/index.js
Labels: refactor, FE, V2

#167 Feat/developer view
  src/api/member.js
  src/api/project.js
  src/features/developer/components/GrowthChart.vue
  src/features/developer/router.js
  src/features/developer/views/DashboardView.vue
  src/features/developer/views/DeveloperDetailView.vue
  src/router/index.js
Labels: feat, FE, V2

#176 feat: 거부 뱃지 label 내용 수정
  src/components/badge/ProjectHistoryStatusBadge.vue
Labels: FE, V2

#180 [fix] 헤더에 프로필 뜨도록 수정
  src/api/member.js
  src/components/header/AuthMenu.vue
  src/features/auth/views/LoginView.vue
  src/features/developer/components/DeveloperFormCard.vue
  src/stores/auth.js
Labels: FE, V2, fix

#181 [refactor] 로그인 권한별 메인 대시보드 이동 문제 해결
  src/features/admin/router.js
  src/features/auth/views/LoginView.vue
  src/features/developer/router.js
  src/router/index.js
Labels: refactor, FE

#183 fix: 헤더에서 알림 삭제, 마이페이지 추가, 프로필 모달 수정
  src/components/header/AuthMenu.vue
  src/components/header/HeaderNav.vue
  src/features/notification/components/NotificationModal.vue
Labels: FE, V2, fix

#187 [fix] 버그 수정
  src/features/project/router.js
  src/features/project/views/ProjectHistoryListView.vue
Labels: FE, fix

#188 [fix] fix project router.js
  src/features/project/router.js
Labels: FE, BUG🐞, fix

#194 [fix] project history tab
  src/features/project/components/ProjectHistoryItem.vue
  src/features/project/components/ProjectHistoryList.vue
  src/features/project/components/StatusFilter.vue
  src/features/project/router.js
  src/features/project/views/ProjectHistoryListView.vue
  src/features/project/views/ProjectListView.vue
Labels: FE, V2, fix

#195 [Refactor] 관리자 대시보드 수정
  src/features/admin/components/dashboard/DeveloperAvailability.vue
  src/features/admin/components/dashboard/DeveloperRankingSlider.vue
  src/features/admin/components/dashboard/ProjectStatusPanel.vue
  src/features/admin/views/AdminDashBoardView.vue
Labels: refactor, FE, V2

#198 [fix] 개발자 상세 페이지 수정
  src/features/developer/components/BarChart.vue
  src/features/developer/views/DeveloperDetailView.vue
Labels: FE, V2, fix

#202 [feat] 개발자 상세 페이지 보유 자격증 조회 스타일 수정
  src/features/developer/views/DeveloperDetailView.vue
Labels: feat, FE, V2

#203 [refactor] 상태 뱃지 추가, 자격증 관련 페이지 리펙토링
  src/features/admin/views/AdminCertificateApprovalView.vue
  src/features/admin/views/AdminCertificateTypeSetting.vue
  src/features/developer/views/DeveloperCertificateTypeListView.vue
  src/features/developer/views/DeveloperListView.vue
  src/features/developer/views/DeveloperOwnedCertificateView.vue
  src/features/squad/components/create/ManualDeveloperList.vue
  src/features/squad/components/modal/FilterModal.vue
Labels: refactor, FE, V2

#206 refactor: 프로젝트 상태 '평가중' 추가 및 색상 통합
  src/features/project/components/FilterSidebar.vue
  src/features/project/components/ProjectCard.vue
  src/features/project/components/StatusIndicator.vue
  src/features/project/views/ProjectListView.vue
Labels: refactor, FE, V2

#207 [Refactor] 프로젝트 세부사항 페이지에서 버튼 수정
  src/features/project/views/ProjectDetailView.vue
  src/features/squad/components/create/ManualDeveloperList.vue
Labels: refactor, FE

#211 [refactor] 통계에서 개발자 item 누르면 해당 개발자 상세 페이지로 연결 & 스타일을 개발자 리스트와 통합
  src/components/list/DevListItem.vue
  src/features/statistics/components/DevList.vue
Labels: refactor, FE, V2

#219 refactor: 프로젝트 등록 페이지 리펙토링
  src/features/project/views/ProjectRegisterView.vue
Labels: refactor, FE, V2

#221 refactor: 라벨 이름 바꿈
  src/components/badge/StatusBadge.vue
Labels: refactor, FE, V2

#244 [refactor] 개발자 메인페이지 교육 추천 수정
  src/features/developer/views/DashboardView.vue
Labels: refactor, FE, V2

#246 Refactor/222 project all update
  src/api/project.js
  src/components/badge/BasicBadge.vue
  src/composable/useNotification.js
  src/features/project/components/AlreadyRequestedModal.vue
  src/features/project/components/FilterSidebar.vue
  src/features/project/components/ProjectCard.vue
  src/features/project/components/ProjectEditForm.vue
  src/features/project/components/ProjectHistoryRegisterCard.vue
  src/features/project/components/ProjectHistoryRejectCard.vue
  src/features/project/components/ProjectModal.vue
  src/features/project/components/SquadCard.vue
  src/features/project/components/StatusIndicator.vue
  src/features/project/router.js
  src/features/project/views/ProjectDetailView.vue
  src/features/project/views/ProjectHistoryRegisterView.vue
  src/features/project/views/ProjectListView.vue
  src/features/squad/components/modal/ConfirmModal.vue
  src/features/squad/router.js
Labels: feat, refactor, FE, V2

#247 Refactor/222 project all update
  src/features/developer/views/DeveloperDetailView.vue
  src/features/project/components/SquadCard.vue
  src/features/squad/components/create/SquadCreateSection.vue
  src/features/squad/components/modal/DeveloperDetailModal.vue
Labels: refactor, FE, V2

#262 Refactor/260 squad list page
  src/features/squad/views/SquadListView.vue
Labels: refactor, FE, V2

#264 [fix] 프로젝트 종료 날짜 보이게 수정
  src/api/squad.js
  src/features/project/components/ProjectEditForm.vue
  src/features/project/views/ProjectDetailView.vue
  src/features/squad/components/create/ManualDeveloperList.vue
  src/features/squad/components/presentation/SquadMemberRenderer.vue
Labels: FE, V2, fix

#266 [fix]: 프로젝트 수정 오류를 수정
  src/features/project/views/ProjectDetailView.vue
Labels: FE, V2, fix

#275 [fix] 통계 - 지속적인 경고 콘솔 문제 해결
  src/features/statistics/views/GradeSalaryView.vue
Labels: refactor, FE, V2

#293 fix: 스쿼드 사이드바, 프로젝트 상세 버튼 수정
  src/features/project/views/ProjectDetailView.vue
  src/features/squad/views/SquadListView.vue
Labels: refactor, FE, V2

#300 fix: 기술 스택별 구성원 조회 기능 수정
  src/features/squad/views/SquadDetailView.vue
  src/features/squad/views/SquadListView.vue
Labels: FE, V2, fix

#303 fix: 버튼 위치 수정
  src/features/project/components/SquadCard.vue
Labels: refactor, FE, V2
